annotations:
  category: Analytics
  images: |
    - name: kibana
      image: docker.io/bitnami/kibana:8.16.1-debian-12-r0
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r33
  licenses: Apache-2.0
apiVersion: v2
appVersion: 8.16.1
description: Kibana is an open source, browser based analytics and search dashboard
  for Elasticsearch. Kibana strives to be easy to get started with, while also being
  flexible and powerful.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/kibana/img/kibana-stack-220x234.png
dependencies:
  - name: common
    version: 2.27.0
keywords:
- kibana
- analytics
- monitoring
- metrics
- logs
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: kibana
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kibana
version: 11.3.2
